theme: jekyll-theme-merlot
title: Abha Jadon
email: "abha.jadon8@gmail.com"
description: "Abha Jadon Profile"
baseurl: ""
url: "http://abha-jadon.github.io"
github_username: abha-jadon
author: Abha Jadon
markdown: kramdown
future: true